language: node_js
node_js:
  - 'lts/*'

install:
  - yarn install

services: mongodb

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

scripts:
  - yarn build
  - yarn test
  - yarn test:cov

after_success:
  - yarn coveralls
